.TH "gdal2tiles" 1 "16 May 2012" "GDAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gdal2tiles \- gdal2tiles.py 
generates directory with TMS tiles, KMLs and simple web viewers
.SH "SYNOPSIS"
.PP
.PP
.nf

gdal2tiles.py [-title "Title"] [-publishurl http://yourserver/dir/]
              [-nogooglemaps] [-noopenlayers] [-nokml]
              [-googlemapskey KEY] [-forcekml] [-v]
              input_file [output_dir]
.fi
.PP
.SH "DESCRIPTION"
.PP
This utility generates a directory with small tiles and metadata, following OSGeo Tile Map Service Specification. Simple web pages with viewers based on Google Maps and OpenLayers are generated as well - so anybody can comfortably explore your maps on-line and you do not need to install or configure any special software (like mapserver) and the map displays very fast in the webbrowser. You only need to upload generated directory into a web server.
.PP
GDAL2Tiles creates also necessary metadata for Google Earth (KML SuperOverlay), in case the supplied map uses EPSG:4326 projection.
.PP
World files and embedded georeference is used during tile generation, but you can publish a picture without proper georeference too.
.PP
.IP "\fB\fB-p\fP \fIPROFILE\fP, --profile=\fIPROFILE\fP: \fP" 1c
Tile cutting profile (mercator,geodetic,raster) - default 'mercator' (Google Maps compatible). 
.IP "\fB\fB-r\fP \fIRESAMPLING\fP, --resampling=\fIRESAMPLING\fP: \fP" 1c
Resampling method (average,near,bilinear,cubic,cubicspline,lanczos,antialias) - default 'average'. 
.IP "\fB\fB-s\fP \fISRS\fP, --s_srs=\fISRS\fP: \fP" 1c
The spatial reference system used for the source input data. 
.IP "\fB\fB-z\fP \fIZOOM\fP, --zoom=\fIZOOM\fP: \fP" 1c
Zoom levels to render (format:'2-5' or '10'). 
.IP "\fB\fB-e\fP, --resume: \fP" 1c
Resume mode. Generate only missing files. 
.IP "\fB\fB-a\fP \fINODATA\fP, --srcnodata=\fINODATA\fP: \fP" 1c
NODATA transparency value to assign to the input data. 
.IP "\fB\fB-v, --verbose\fP \fP" 1c
Generate verbose output of tile generation. 
.IP "\fB\fB-h, --help\fP \fP" 1c
Show help message and exit. 
.IP "\fB\fB--version\fP \fP" 1c
Show program's version number and exit. 
.PP
.PP
\fBKML (Google Earth) options:\fP
.PP
Options for generated Google Earth SuperOverlay metadata 
.IP "\fB\fB-k, --force-kml\fP \fP" 1c
Generate KML for Google Earth - default for 'geodetic' profile and 'raster' in EPSG:4326. For a dataset with different projection use with caution! 
.IP "\fB\fB-n, --no-kml\fP: \fP" 1c
Avoid automatic generation of KML files for EPSG:4326. 
.IP "\fB\fB-u\fP \fIURL\fP, --url=\fIURL\fP: \fP" 1c
URL address where the generated tiles are going to be published. 
.PP
.PP
\fBWeb viewer options:\fP
.PP
Options for generated HTML viewers a la Google Maps 
.IP "\fB\fB-w\fP \fIWEBVIEWER\fP, --webviewer=\fIWEBVIEWER\fP: \fP" 1c
Web viewer to generate (all,google,openlayers,none) - default 'all'. 
.IP "\fB\fB-t\fP \fITITLE\fP, --title=\fITITLE\fP: \fP" 1c
Title of the map. 
.IP "\fB\fB-c\fP \fICOPYRIGHT\fP, --copyright=\fICOPYRIGHT\fP: \fP" 1c
Copyright for the map. 
.IP "\fB\fB-g\fP \fIGOOGLEKEY\fP, --googlekey=\fIGOOGLEKEY\fP: \fP" 1c
Google Maps API key from http://code.google.com/apis/maps/signup.html. 
.IP "\fB\fB-y\fP \fIYAHOOKEY\fP, --yahookey=\fIYAHOOKEY\fP: \fP" 1c
Yahoo Application ID from http://developer.yahoo.com/wsregapp/. 
.PP
.PP
NOTE: gdal2tiles.py is a Python script that needs to be run against 'new generation' Python GDAL binding.
.SH "AUTHORS"
.PP
Klokan Petr Pridal <klokan@klokan.cz> as a Google SoC 2007 Project. 
